name: Check the source code
on:
  pull_request:
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install packages
        run: npm ci
      - name: Check js,ts type,format
        run: npm run fix
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Format Change
          branch: ${{ github.head_ref }}
