name: Check the source code
on:
  pull_request:
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - name: Install packages
        run: npm install
      - name: exec ESlint Prettier
        run: npm run fix
      - name: Cache php-cs-fixer
        uses: actions/cache@v2
        id: cache_php_cs_fixer
        env:
          cache-name: cache-php-cs-fixer
        with:
          path: ./tools/php-cs-fixer/vendor
          key: --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: install php-cs-fixer
        if: steps.cache_php_cs_fixer.outputs.cache-hit != 'true'
        run: composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer --with-all-dependencies
      - name: exec php-cs-fixer
        run: |
          tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php --diff
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Format Change
          branch: ${{ github.head_ref }}
